name: Generate Javadoc

on:
  push:
    branches:
      - main
      - fardeenfs-patch-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build javadoc

      - name: Deploy Javadoc
        uses: actions/upload-artifact@v2
        with:
          name: javadoc
          path: javadocs